CREATE DATABASE IF NOT EXISTS `restaurant`;

USE `restaurant`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE IF NOT EXISTS `users` (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username    VARCHAR(255) NOT NULL,
  password    TEXT NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;
